version: '3.7'

services:
  app:
    build:
      context: .
      args:
        PIPENV_INSTALL_OPTIONS: --dev
    environment:
    - DJANGO_MANAGEPY_COLLECTSTATIC=off
    - DEV_MODE=on
    - DJANGO_SETTINGS_MODULE=app.settings
    - ALLOWED_HOSTS=*
    - EMAIL_HOST=mail
    - EMAIL_PORT=1025
    - RDS_HOSTNAME=db
    - RDS_PORT=5432
    - RDS_DB_NAME=postgres
    - RDS_USERNAME=postgres
    - RDS_PASSWORD=password
    volumes:
    - .:/code
    depends_on:
      db:
        condition: service_healthy
      mail:
        condition: service_healthy
    ports:
    - "8000:8000"
    command: ['python', './manage.py', 'runserver', '0.0.0.0:8000']

  mail:
    image: accent/mailhog
    expose:
    - "1025"
    ports:
    - "8025:8025"
    healthcheck:
      test: ["CMD-SHELL", "exit 0"]

  db:
    image: postgres:latest
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=postgres
    - POSTGRES_INITDB_ARGS=--auth-host=md5
    - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
    - postgres:/var/lib/postgresql/data/pgdata
    ports:
    - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres:
