version: 2
jobs:
  build:
    working_directory: ~/django_boilerplate
    docker:
      - image: circleci/python:3.6
        environment:
          ALLOWED_HOSTS: "*"
          RDS_HOSTNAME: 127.0.0.1
          RDS_PORT: 5432
          RDS_DB_NAME: db
          RDS_USERNAME: postgres
          RDS_PASSWORD: password
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run: sudo chown -R circleci:circleci /usr/local/share
      - restore_cache:
          key: deps-{{ checksum "requirements/base.txt" }}-{{ checksum "requirements/dev.txt" }}
      - run:
          command: |
            pip install -r requirements/dev.txt
      - save_cache:
          key: deps-{{ checksum "requirements/base.txt" }}-{{ checksum "requirements/dev.txt" }}
          paths:
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
            - "/usr/local/share"
      - run:
          command: |
            make test
      - store_test_results:
          path: htmlcov
      - store_artifacts:
          path: htmlcov
          destination: coverage
